image: ubuntu:18.04


before_script:
    - apt update && apt install -y file patch curl build-essential libncurses5-dev libncursesw5-dev rsync
    - curl -O https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh
    - bash Anaconda3-2019.03-Linux-x86_64.sh -b -p "$PWD/anaconda"
    - export PATH="$PWD/anaconda/bin:$PATH"

.build_template: &build_definition
    script:
        - conda build recipe/toolchain

.artifacts_template: &artifacts_definition
    artifacts:
        when: on_failure
        paths:
            - "$PWD/anaconda/conda-bld"
        expire_in: 1 week
    artifacts:
        when: on_success
        paths:
            - "$PWD/anaconda/conda-bld/linux-64/toolchain-${TOOLCHAIN_VARIANT}*.tar.bz2"
        expire_in: 1 week

# RISC-V32
riscv32-linux-musl:
    variables:
        TOOLCHAIN_VARIANT: riscv32-linux-musl
    <<: *build_definition
    <<: *artifacts_definition

riscv32-elf-nostdc:
    variables:
        TOOLCHAIN_VARIANT: riscv32-elf-nostdc
    <<: *build_definition
    <<: *artifacts_definition

riscv32-elf-newlib:
    variables:
        TOOLCHAIN_VARIANT: riscv32-elf-newlib
    <<: *build_definition
    <<: *artifacts_definition

# OR1K
or1k-elf-nostdc:
    variables:
        TOOLCHAIN_VARIANT: or1k-elf-nostdc
    <<: *build_definition
    <<: *artifacts_definition

or1k-elf-newlib:
    variables:
        TOOLCHAIN_VARIANT: or1k-elf-newlib
    <<: *build_definition
    <<: *artifacts_definition

or1k-linux-musl:
    variables:
        TOOLCHAIN_VARIANT: or1k-linux-musl
    <<: *build_definition
    <<: *artifacts_definition

# LM32
lm32-elf-nostdc:
    variables:
        TOOLCHAIN_VARIANT: lm32-elf-nostdc
    <<: *build_definition
    <<: *artifacts_definition

lm32-elf-newlib:
    variables:
        TOOLCHAIN_VARIANT: lm32-elf-newlib
    <<: *build_definition
    <<: *artifacts_definition

